# This file is automatically generated from cmake-kits.json and should be modified only if compiling from CLI
if (NOT DEFINED ENV{ARMGCC_DIR})
	SET(ARMGCC_DIR C:/Users/beasa/.mcuxpressotools/arm-gnu-toolchain-12.2.rel1-mingw-w64-i686-arm-none-eabi)
endif()
