/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    //pinctrl_hog();
    //pinctrl_backlight();
    pinctrl_adc();
    //pinctrl_fec();
//     pinctrl_flexcan1();
//     pinctrl_flexcan2();
//     pinctrl_gpio_led();
//     pinctrl_lpddr4();
//     pinctrl_earc();
//     pinctrl_hdmi();
//     pinctrl_i2c1();
//     pinctrl_i2c2();
//     pinctrl_i2c5();
//     //pinctrl_jtag();
//     pinctrl_lvds0();
//     pinctrl_pmic();
//     pinctrl_flexspi0();
//     pinctrl_sai3_audio();
//     pinctrl_sai5_mic();
//     pinctrl_snvs();
//     pinctrl_wdog();
//     pinctrl_uart1_485();
       //pinctrl_uart2_gnss1();
//     pinctrl_uart3_gnss2();
//     pinctrl_uart4_485();
//     pinctrl_usb1_vbus();
//     pinctrl_usdhc2();
//     pinctrl_usdhc3();
//     pinctrl_usb1();
//     pinctrl_usb2();
//     pinctrl_bat_ic();
//     pinctrl_eqos();
//     pinctrl_fram();
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_hog
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_hog(void) {                                   /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_HDMI_CEC_HDMIMIX_HDMI_CEC, 0U);
    IOMUXC_SetPinConfig(IOMUXC_HDMI_CEC_HDMIMIX_HDMI_CEC, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
    IOMUXC_SetPinMux(IOMUXC_HDMI_DDC_SCL_HDMIMIX_HDMI_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_HDMI_DDC_SCL_HDMIMIX_HDMI_SCL, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_HDMI_DDC_SDA_HDMIMIX_HDMI_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_HDMI_DDC_SDA_HDMIMIX_HDMI_SDA, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_HDMI_HPD_HDMIMIX_HDMI_HPD, 0U);
    IOMUXC_SetPinConfig(IOMUXC_HDMI_HPD_HDMIMIX_HDMI_HPD, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI1_MCLK_GPIO4_IO20, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI1_MCLK_GPIO4_IO20, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD0_GPIO4_IO12, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI1_TXD0_GPIO4_IO12, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U));
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD7_GPIO4_IO19, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI1_TXD7_GPIO4_IO19, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI2_RXFS_GPIO4_IO21, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI2_RXFS_GPIO4_IO21, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI5_RXC_GPIO3_IO20, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_backlight
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_backlight(void) {                             /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SPDIF_EXT_CLK_PWM1_OUT, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SPDIF_EXT_CLK_PWM1_OUT, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_adc
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_adc(void) {                                   /*!< Function assigned for the core: Cortex-A53[a53_0] */
    // IOMUXC_SetPinMux(IOMUXC_ECSPI2_SS0_ECSPI2_SS0, 0U);
    // IOMUXC_SetPinConfig(IOMUXC_ECSPI2_SS0_ECSPI2_SS0, 
    //                     IOMUXC_SW_PAD_CTL_PAD_DSE(0U) |
    //                     IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);

    // IOMUXC_SetPinMux(IOMUXC_I2C3_SCL_ECSPI2_SCLK, 0U);
    // IOMUXC_SetPinConfig(IOMUXC_I2C3_SCL_ECSPI2_SCLK, 
    //                      IOMUXC_SW_PAD_CTL_PAD_DSE(0U) |
    //                      IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);

    // IOMUXC_SetPinMux(IOMUXC_I2C3_SDA_ECSPI2_MOSI, 0U);
    // IOMUXC_SetPinConfig(IOMUXC_I2C3_SDA_ECSPI2_MOSI, 
    //                     IOMUXC_SW_PAD_CTL_PAD_DSE(0U) |
    //                     IOMUXC_SW_PAD_CTL_PAD_PE_MASK);

    // IOMUXC_SetPinMux(IOMUXC_I2C4_SCL_ECSPI2_MISO, 0U);
    // IOMUXC_SetPinConfig(IOMUXC_I2C4_SCL_ECSPI2_MISO, 
    //                     IOMUXC_SW_PAD_CTL_PAD_DSE(0U) |
    //                     IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);

    // IOMUXC_SetPinMux(IOMUXC_SAI3_RXD_GPIO4_IO30, 0U);
    // IOMUXC_SetPinConfig(IOMUXC_SAI3_RXD_GPIO4_IO30, 
    //                     IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
    //                     IOMUXC_SW_PAD_CTL_PAD_PE_MASK);


    IOMUXC_SetPinMux(IOMUXC_I2C3_SCL_ECSPI2_SCLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C3_SCL_ECSPI2_SCLK, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_I2C3_SDA_ECSPI2_MOSI, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C3_SDA_ECSPI2_MOSI, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    
    
    IOMUXC_SetPinMux(IOMUXC_I2C4_SCL_ECSPI2_MISO, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C4_SCL_ECSPI2_MISO, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_SS0_ECSPI2_SS0, 0U);
    IOMUXC_SetPinConfig(IOMUXC_ECSPI2_SS0_ECSPI2_SS0, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    //pd/rst
    IOMUXC_SetPinMux(IOMUXC_SD2_CD_B_GPIO2_IO12, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD2_CD_B_GPIO2_IO12, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);


    IOMUXC_SetPinMux(IOMUXC_SAI1_MCLK_GPIO4_IO20, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI1_MCLK_GPIO4_IO20,
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);

    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD0_GPIO4_IO12, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI1_TXD0_GPIO4_IO12,
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);

    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD7_GPIO4_IO19, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI1_TXD7_GPIO4_IO19,
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);

    IOMUXC_SetPinMux(IOMUXC_SAI2_RXFS_GPIO4_IO21, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI2_RXFS_GPIO4_IO21,
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_fec
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_fec(void) {                                   /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD6_ENET1_RGMII_RD2, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD7_ENET1_RGMII_RD3, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXC_ENET1_RGMII_RXC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD2_ENET1_RGMII_TD2, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD3_ENET1_RGMII_TD3, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD4_ENET1_RGMII_TX_CTL, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXD5_ENET1_RGMII_TXC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI1_TXFS_ENET1_RGMII_RX_CTL, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CLK_ENET1_MDC, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_CMD_ENET1_MDIO, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA0_ENET1_RGMII_TD1, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA1_ENET1_RGMII_TD0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA2_ENET1_RGMII_RD0, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD1_DATA3_ENET1_RGMII_RD1, 0U);
    IOMUXC_SetPinMux(IOMUXC_SD2_WP_GPIO2_IO20, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_flexcan1
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_flexcan1(void) {                              /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI2_TXC_CAN1_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI2_TXC_CAN1_RX, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SPDIF_TX_CAN1_TX, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_flexcan2
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_flexcan2(void) {                              /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI2_MCLK_CAN2_RX, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI2_TXD0_CAN2_TX, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_gpio_led
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_gpio_led(void) {                              /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO12_GPIO1_IO12, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_lpddr4
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_lpddr4(void) {                                /*!< Function assigned for the core: Cortex-A53[a53_0] */
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_earc
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_earc(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_hdmi
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_hdmi(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_HDMI_CEC_HDMIMIX_HDMI_CEC, 0U);
    IOMUXC_SetPinMux(IOMUXC_HDMI_DDC_SCL_HDMIMIX_HDMI_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_HDMI_DDC_SDA_HDMIMIX_HDMI_SDA, 0U);
    IOMUXC_SetPinMux(IOMUXC_HDMI_HPD_HDMIMIX_HDMI_HPD, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_i2c1
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_i2c1(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_I2C1_SCL_I2C1_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C1_SCL_I2C1_SCL, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_I2C1_SDA_I2C1_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C1_SDA_I2C1_SDA, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_i2c2
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_i2c2(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_I2C2_SCL_I2C2_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C2_SCL_I2C2_SCL, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_ODE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_I2C2_SDA_I2C2_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C2_SDA_I2C2_SDA, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_ODE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_i2c5
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_i2c5(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI5_MCLK_I2C5_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI5_MCLK_I2C5_SDA, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_ODE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI5_RXD0_I2C5_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI5_RXD0_I2C5_SCL, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
                        IOMUXC_SW_PAD_CTL_PAD_ODE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_jtag
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
// void pinctrl_jtag(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
//     IOMUXC_SetPinConfig(IOMUXC_JTAG_MOD, 
//                         IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
//                         IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
//                         IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
//     IOMUXC_SetPinConfig(IOMUXC_JTAG_TCK, 
//                         IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
//                         IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
//                         IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
//     IOMUXC_SetPinConfig(IOMUXC_JTAG_TDI, 
//                         IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
//                         IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
//                         IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
//     IOMUXC_SetPinConfig(IOMUXC_JTAG_TDO,
//                         IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
//                         IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
//                         IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
//     IOMUXC_SetPinConfig(IOMUXC_JTAG_TMS, 
//                         IOMUXC_SW_PAD_CTL_PAD_DSE(2U) |
//                         IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
//                         IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
// }


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_lvds0
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_lvds0(void) {                                 /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI5_RXFS_GPIO3_IO19, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_pmic
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_pmic(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO03_GPIO1_IO03, 0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO1_IO03_GPIO1_IO03, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_flexspi0
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_flexspi0(void) {                              /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_NAND_ALE_FLEXSPI_A_SCLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_NAND_ALE_FLEXSPI_A_SCLK, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE0_B_FLEXSPI_A_SS0_B, 0U);
    IOMUXC_SetPinConfig(IOMUXC_NAND_CE0_B_FLEXSPI_A_SS0_B, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA00_FLEXSPI_A_DATA0, 0U);
    IOMUXC_SetPinConfig(IOMUXC_NAND_DATA00_FLEXSPI_A_DATA0, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA01_FLEXSPI_A_DATA1, 0U);
    IOMUXC_SetPinConfig(IOMUXC_NAND_DATA01_FLEXSPI_A_DATA1, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA02_FLEXSPI_A_DATA2, 0U);
    IOMUXC_SetPinConfig(IOMUXC_NAND_DATA02_FLEXSPI_A_DATA2, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA03_FLEXSPI_A_DATA3, 0U);
    IOMUXC_SetPinConfig(IOMUXC_NAND_DATA03_FLEXSPI_A_DATA3, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_NAND_DQS_FLEXSPI_A_DQS, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_sai3_audio
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_sai3_audio(void) {                            /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI3_MCLK_AUDIOMIX_SAI3_MCLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI3_MCLK_AUDIOMIX_SAI3_MCLK, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI3_TXC_AUDIOMIX_SAI3_TX_BCLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI3_TXC_AUDIOMIX_SAI3_TX_BCLK, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI3_TXD_AUDIOMIX_SAI3_TX_DATA0, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI3_TXD_AUDIOMIX_SAI3_TX_DATA0, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI3_TXFS_AUDIOMIX_SAI3_TX_SYNC, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_sai5_mic
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_sai5_mic(void) {                              /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI3_RXC_AUDIOMIX_PDM_CLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_SAI3_RXFS_AUDIOMIX_PDM_BIT_STREAM0, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_snvs
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_snvs(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_wdog
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_wdog(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO02_WDOG1_WDOG_B, 0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO1_IO02_WDOG1_WDOG_B, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_uart1_485
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_uart1_485(void) {                             /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SAI2_RXC_UART1_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI2_RXC_UART1_RX, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SAI2_TXFS_UART1_RTS_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART1_TXD_UART1_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART1_TXD_UART1_TX, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_uart2_gnss1
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_uart2_gnss1(void) {                           /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_UART2_RXD_UART2_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART2_RXD_UART2_RX, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK);
    IOMUXC_SetPinMux(IOMUXC_UART2_TXD_UART2_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART2_TXD_UART2_TX, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_uart3_gnss2
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_uart3_gnss2(void) {                           /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_UART3_RXD_UART3_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART3_RXD_UART3_RX, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_UART3_TXD_UART3_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART3_TXD_UART3_TX, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_uart4_485
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_uart4_485(void) {                             /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_MISO_UART4_RTS_B, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_MOSI_UART4_TX, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI2_SCLK_UART4_RX, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_usb1_vbus
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_usb1_vbus(void) {                             /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO14_GPIO1_IO14, 0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO1_IO14_GPIO1_IO14, 
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_usdhc2
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_usdhc2(void) {                                /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO04_USDHC2_VSELECT, 0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO1_IO04_USDHC2_VSELECT, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD2_CLK_USDHC2_CLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD2_CLK_USDHC2_CLK, 
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD2_CMD_USDHC2_CMD, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD2_CMD_USDHC2_CMD, 
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA0_USDHC2_DATA0, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD2_DATA0_USDHC2_DATA0, 
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA1_USDHC2_DATA1, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD2_DATA1_USDHC2_DATA1, 
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA2_USDHC2_DATA2, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD2_DATA2_USDHC2_DATA2, 
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD2_DATA3_USDHC2_DATA3, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD2_DATA3_USDHC2_DATA3, 
                        IOMUXC_SW_PAD_CTL_PAD_FSEL_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_HYS_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD2_RESET_B_USDHC2_RESET_B, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_usdhc3
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_usdhc3(void) {                                /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_NAND_CE1_B_USDHC3_STROBE, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE2_B_USDHC3_DATA5, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CE3_B_USDHC3_DATA6, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_CLE_USDHC3_DATA7, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA04_USDHC3_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA05_USDHC3_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA06_USDHC3_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_DATA07_USDHC3_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_RE_B_USDHC3_DATA4, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_WE_B_USDHC3_CLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_NAND_WP_B_USDHC3_CMD, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_usb1
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_usb1(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO00_GPIO1_IO00, 0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO1_IO00_GPIO1_IO00, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U));
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_usb2
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_usb2(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SPDIF_RX_GPIO5_IO04, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SPDIF_RX_GPIO5_IO04, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U));
    IOMUXC_SetPinMux(IOMUXC_UART1_RXD_GPIO5_IO22, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART1_RXD_GPIO5_IO22, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U));
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_bat_ic
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_bat_ic(void) {                                /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_GPIO1_IO01_GPIO1_IO01, 0U);
    IOMUXC_SetPinConfig(IOMUXC_GPIO1_IO01_GPIO1_IO01, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK);
    IOMUXC_SetPinMux(IOMUXC_SD1_RESET_B_GPIO2_IO10, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SD1_RESET_B_GPIO2_IO10, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(1U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_UART4_RXD_I2C6_SCL, 0U);
    IOMUXC_SetPinMux(IOMUXC_UART4_TXD_I2C6_SDA, 0U);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_eqos
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_eqos(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : pinctrl_fram
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void pinctrl_fram(void) {                                  /*!< Function assigned for the core: Cortex-A53[a53_0] */
    IOMUXC_SetPinMux(IOMUXC_SD2_CD_B_GPIO2_IO12, 0U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
